import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 color tokens from UI reference
        error: "#ba1a1a",
        outline: "#6e7977",
        "surface-container-lowest": "#ffffff",
        secondary: "#2b6954",
        "on-surface": "#151c27",
        "inverse-on-surface": "#ebf1ff",
        tertiary: "#7f4025",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d3daea",
        surface: "#f9f9ff",
        "secondary-fixed-dim": "#95d3ba",
        "primary-fixed": "#9cf2e8",
        "surface-container-high": "#e2e8f8",
        "inverse-primary": "#80d5cb",
        "on-secondary": "#ffffff",
        background: "#f9f9ff",
        "on-tertiary-fixed-variant": "#72361b",
        "on-primary-fixed": "#00201d",
        "on-surface-variant": "#3e4947",
        "surface-container-low": "#f0f3ff",
        "on-background": "#151c27",
        "on-tertiary-fixed": "#370e00",
        "secondary-fixed": "#b0f0d6",
        "outline-variant": "#bdc9c6",
        "primary-fixed-dim": "#80d5cb",
        "on-secondary-fixed-variant": "#0b513d",
        "on-tertiary-container": "#ffe5db",
        "surface-container-highest": "#dce2f3",
        "surface-tint": "#006a63",
        "on-primary-container": "#a3faef",
        "surface-container": "#e7eefe",
        "on-primary": "#ffffff",
        "tertiary-container": "#9c573a",
        "on-secondary-fixed": "#002117",
        "tertiary-fixed": "#ffdbce",
        "secondary-container": "#adedd3",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed-dim": "#ffb598",
        "on-secondary-container": "#306d58",
        "on-primary-fixed-variant": "#00504a",
        "primary-container": "#0f766e",
        "error-container": "#ffdad6",
        "inverse-surface": "#2a313d",
        "on-error-container": "#93000a",
        "surface-variant": "#dce2f3",
        primary: "#005c55",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        lexend: ["Lexend", "sans-serif"],
        sans: ["Lexend", "sans-serif"],
      },
      fontSize: {
        h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "status-badge": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "grid-margin": "24px",
        "grid-gutter": "16px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.6s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "count-up": "countUp 0.8s ease-out",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 1.5s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(0, 92, 85, 0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(0, 92, 85, 0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      backgroundImage: {
        "islamic-pattern": "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 0l2.5 12.5L45 15l-12.5 2.5L30 30l-2.5-12.5L15 15l12.5-2.5z' fill='%230f766e' fill-opacity='0.04' fill-rule='evenodd'/%3E%3C/svg%3E\")",
        "hero-gradient": "linear-gradient(135deg, #003d38 0%, #005c55 40%, #007a71 70%, #004d47 100%)",
      },
      boxShadow: {
        "ambient": "0 10px 40px -10px rgba(15, 118, 110, 0.1)",
        "card": "0 2px 12px rgba(0, 0, 0, 0.06)",
        "elevated": "0 8px 32px rgba(0, 92, 85, 0.15)",
      },
    },
  },
  plugins: [],
};

export default config;
